local Remap = require("laborda.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<leader>fg", ":Telescope")
nnoremap("<leader>fs", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<leader>fg", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<leader>ff", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<leader>fc", function()
    require('telescope.builtin').find_files({ cwd = vim.fn.expand('%:p:h') })
end)

nnoremap("<leader>pw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>fb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>fh", function()
    require('telescope.builtin').help_tags()
end)

nnoremap("<leader>fdf", function()
    require('laborda.telescope').search_dotfiles({ hidden = true })
end)
nnoremap("<leader>gc", function()
    require('laborda.telescope').git_branches()
end)
nnoremap("<leader>gw", function()
    require('telescope').extensions.git_worktree.git_worktrees()
end)
nnoremap("<leader>gm", function()
    require('telescope').extensions.git_worktree.create_git_worktree()
end)
nnoremap("<leader>gd", function()
    require('telescope.builtin').lsp_definitions()
end)
nnoremap("<leader>gD", function()
    require('telescope.builtin').lsp_type_definitions()
end)
nnoremap("<leader>di", function()
    require('telescope.builtin').diagnostics({ bufnr = 0 })
end)
